# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: ghd-example

gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org

before:
  hooks:
    - go test ./...

builds:
  - id: ghd-example
    main: ./cmd/ghd-example
    binary: ghd-example
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -buildid=
      - -X main.version={{ .Version }}
      - -X main.commit={{ .FullCommit }}
      - -X main.date={{ .Date }}

archives:
  - id: ghd-example
    ids:
      - ghd-example
    formats:
      - binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

sboms:
  - artifacts: binary

snapshot:
  version_template: "{{ .Env.GHD_EXAMPLE_VERSION }}"

changelog:
  disable: true
