# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2
pro: true

project_name: ghd-example

monorepo:
  tag_prefix: example-

before:
  hooks:
    - go test ./...

builds:
  - id: ghd-example
    main: ./cmd/ghd-example
    binary: ghd-example
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -buildid=
      - -X main.version={{ .Version }}
      - -X main.commit={{ .FullCommit }}
      - -X main.date={{ .Date }}

archives:
  - id: ghd-example
    ids:
      - ghd-example
    formats:
      - binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

sboms:
  - artifacts: binary

release:
  draft: true
  use_existing_draft: true
  replace_existing_artifacts: true
  make_latest: false
  mode: keep-existing

changelog:
  disable: true
